/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import static application.Application.*;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import application.Dessin;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.HashSet;
import metier.*;

/**
 *
 * @author mathi_tn3kay8
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenPrincipal
     */
    
    boolean visible = true;
    File file;
    int nbVoisins = 0;
    int recherche = 0;
    Ville villeSelec = new Musee("vide","vide");
    Ville v1 = new Musee("vide", "vide");
    Ville v2 = new Musee("vide", "vide");
    boolean voisinOnOf = false;
    
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bouttonAgrandir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bouttonFermer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bouttonMenu = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        infosVilleSelec = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        boutonNomVille = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boutonTypeVille = new javax.swing.JLabel();
        bouttonQuantite = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        spinnerNbVoisins = new javax.swing.JSpinner();
        boutonOnOf = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bouttonAPropos = new javax.swing.JButton();
        sliderTailleSommets = new javax.swing.JSlider();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        boutonAProposSelection = new javax.swing.JButton();
        jLabelVille1 = new javax.swing.JLabel();
        jLabelVille2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        panelGraph = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Map Analitic");
        setBackground(new java.awt.Color(51, 51, 255));
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        Header.setBackground(new java.awt.Color(0, 0, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        bouttonAgrandir.setBackground(new java.awt.Color(0, 0, 102));
        bouttonAgrandir.setPreferredSize(new java.awt.Dimension(75, 30));
        bouttonAgrandir.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full_screen.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        bouttonAgrandir.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.add(bouttonAgrandir, java.awt.BorderLayout.LINE_START);

        bouttonFermer.setBackground(new java.awt.Color(0, 0, 102));
        bouttonFermer.setLayout(new java.awt.BorderLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        bouttonFermer.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel4.add(bouttonFermer, java.awt.BorderLayout.CENTER);

        Header.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sans titre.png"))); // NOI18N
        jLabel4.setText("SAE GRAMA");
        jPanel6.add(jLabel4, java.awt.BorderLayout.CENTER);

        Header.add(jPanel6, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menuBar.setPreferredSize(new java.awt.Dimension(350, 450));
        menuBar.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 470));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bouttonMenu.setBackground(new java.awt.Color(0, 0, 102));
        bouttonMenu.setPreferredSize(new java.awt.Dimension(40, 40));
        bouttonMenu.setLayout(new java.awt.BorderLayout());

        labelMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        labelMenu.setPreferredSize(new java.awt.Dimension(50, 32));
        labelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMenuMouseExited(evt);
            }
        });
        bouttonMenu.add(labelMenu, java.awt.BorderLayout.CENTER);

        jPanel1.add(bouttonMenu, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "gestionnaire map", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setAutoscrolls(true);
        jPanel8.setMinimumSize(new java.awt.Dimension(300, 135));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 135));

        jButton1.setText("importer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel8.add(jButton1);

        jButton2.setText("supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);

        jButton3.setText("charger");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel8.add(jButton3);

        jPanel2.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        infosVilleSelec.setBackground(new java.awt.Color(0, 0, 102));
        infosVilleSelec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ville selectionnee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton5.setText("details");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        infosVilleSelec.add(jButton5);

        jButton6.setText("unselect");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        infosVilleSelec.add(jButton6);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   ville selec :   ");
        infosVilleSelec.add(jLabel6);

        boutonNomVille.setForeground(new java.awt.Color(255, 255, 255));
        boutonNomVille.setText("Aucune");
        infosVilleSelec.add(boutonNomVille);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("type de ville :");
        infosVilleSelec.add(jLabel7);

        boutonTypeVille.setForeground(new java.awt.Color(255, 255, 255));
        boutonTypeVille.setText("Aunun");
        infosVilleSelec.add(boutonTypeVille);

        bouttonQuantite.setText("detail Qte");
        bouttonQuantite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouttonQuantiteMouseClicked(evt);
            }
        });
        infosVilleSelec.add(bouttonQuantite);

        jPanel2.add(infosVilleSelec, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        menuBar.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 470));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 153));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "parametres de la map", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setMinimumSize(new java.awt.Dimension(10, 300));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 180));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(0, 0, 153));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nombre de voisins");
        jPanel12.add(jLabel5);

        jButton4.setText("?");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel12.add(jButton4);

        spinnerNbVoisins.setPreferredSize(new java.awt.Dimension(100, 22));
        spinnerNbVoisins.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerNbVoisinsStateChanged(evt);
            }
        });
        jPanel12.add(spinnerNbVoisins);

        boutonOnOf.setText("Of");
        boutonOnOf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonOnOfMouseClicked(evt);
            }
        });
        jPanel12.add(boutonOnOf);

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(0, 0, 153));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("taille des sommets");
        jPanel13.add(jLabel3);

        bouttonAPropos.setText("?");
        bouttonAPropos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouttonAProposMouseClicked(evt);
            }
        });
        jPanel13.add(bouttonAPropos);

        sliderTailleSommets.setToolTipText("taille des sommets");
        sliderTailleSommets.setPreferredSize(new java.awt.Dimension(150, 20));
        sliderTailleSommets.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTailleSommetsStateChanged(evt);
            }
        });
        jPanel13.add(sliderTailleSommets);

        jPanel9.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel7.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(0, 0, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "autres parametres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("       selection multiple       ");
        jPanel10.add(jLabel8);

        jButton8.setText("selection");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel10.add(jButton8);

        jButton7.setText("annuler");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel10.add(jButton7);

        boutonAProposSelection.setText("?");
        boutonAProposSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAProposSelectionMouseClicked(evt);
            }
        });
        jPanel10.add(boutonAProposSelection);

        jLabelVille1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVille1.setText("    Ville 1 : Aucune");
        jPanel10.add(jLabelVille1);

        jLabelVille2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVille2.setText("   Ville 2 : Aucune");
        jPanel10.add(jLabelVille2);

        jButton9.setText("itineraire");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel10.add(jButton9);

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        menuBar.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(menuBar, java.awt.BorderLayout.LINE_START);

        panelGraph.setBackground(new java.awt.Color(230, 230, 230));
        panelGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGraphMouseClicked(evt);
            }
        });
        panelGraph.setLayout(new java.awt.BorderLayout());
        panelGraph.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelGraph, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel j, Color c) {
        j.setBackground(c);
    }
    
    public void cacherMontrer(JPanel j, boolean visible, JLabel l) {
        if(visible) {
            menuBar.setPreferredSize(new Dimension(120, menuBar.getHeight()));
            changerImage(l, "/icon/menu.png");
        }
        else {
            menuBar.setPreferredSize(new Dimension(350, menuBar.getHeight()));
            changerImage(l, "/icon/back.png");
        }
    }
    
    public void changerImage(JLabel l, String nomImage) {
        ImageIcon nvImage = new ImageIcon(getClass().getResource(nomImage));
        l.setIcon(nvImage);
    }
    
    public boolean rechercherVille(int cX, int cY, Ville v) {
        
        int tailleSpe = sliderTailleSommets.getValue() / 2;
        
        if (cX - tailleSpe <= v.getCordX() &&
        v.getCordX() <= cX + tailleSpe &&
        cY - tailleSpe <= v.getCordY() &&
        v.getCordY() <= cY + tailleSpe) {
            return true;
        }
        return false;
    }
    
    public ArrayList<Ville> rechercheVoisins(Ville v) {
        ArrayList<Ville> ret = new ArrayList<>();
        ret.add(v);
        
        for (int i=0;i<nbVoisins;i++) {
            ret = bouclage(ret);
        }
        return ret;
    }
    
    public ArrayList<Ville> bouclage(ArrayList<Ville> ret) {
        ArrayList<Ville> retBuffer = new ArrayList<>();
        
        for (Ville vPrim : ret) {
            for (Ville vi : gr.getListe()) {
                if (vPrim.getNomVille().equals(vi.getNomVille())) {
                    for(Ville vPrimPrim : vi.getVoisins()) {
                        retBuffer.add(vPrimPrim);
                    }
                }
            }
            
        }
        for (Ville vv : retBuffer) {
            if (!ret.contains(vv)) {
                ret.add(vv);
            }
        }
        return ret;
    }
    
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        changeColor(bouttonAgrandir, new Color(0,0,152));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        changeColor(bouttonAgrandir, new Color(0,0,102));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(this.getExtendedState() != MenuPrincipal.MAXIMIZED_BOTH) {
            this.setExtendedState(MenuPrincipal.MAXIMIZED_BOTH);
        }
        else {
            this.setExtendedState(MenuPrincipal.NORMAL);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        changeColor(bouttonFermer, new Color(0,0,152));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        changeColor(bouttonFermer, new Color(0,0,102));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void labelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMouseExited
        changeColor(bouttonMenu, new Color(0,0,102));
    }//GEN-LAST:event_labelMenuMouseExited

    private void labelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMouseEntered
        changeColor(bouttonMenu, new Color(0,0,152));
    }//GEN-LAST:event_labelMenuMouseEntered

    private void labelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMouseClicked

        if(visible) {
            cacherMontrer(menuBar, visible, labelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            visible = false;
        }
        else {
            cacherMontrer(menuBar, visible, labelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            visible = true;
        }
    }//GEN-LAST:event_labelMenuMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Dessin.clear(panelGraph);
        Dessin.dessinerGraph(panelGraph, gr.getListe(), gr);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dessin.clear(panelGraph);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sliderTailleSommetsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTailleSommetsStateChanged
        Dessin.setTailleSommets(sliderTailleSommets.getValue());
    }//GEN-LAST:event_sliderTailleSommetsStateChanged

    private void bouttonAProposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonAProposMouseClicked
        JOptionPane.showMessageDialog(this, "La taille des sommets est actuellement de " + sliderTailleSommets.getValue() + " px !", "Bot", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bouttonAProposMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        JOptionPane.showMessageDialog(this, "Distance de voisins actuellement affiches : " + spinnerNbVoisins.getValue() + " voisins !\nPour activer et desactiver la fonction il faut cliquer sur \nOn / Of et selectionner une ville !", "Bot", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4MouseClicked

    private void spinnerNbVoisinsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerNbVoisinsStateChanged
        if ( (int) spinnerNbVoisins.getValue() > 4 ) {
            spinnerNbVoisins.setValue(4);
        } else if ((int) spinnerNbVoisins.getValue() < 0 ) {
            spinnerNbVoisins.setValue(0);
        }
        nbVoisins = (int) spinnerNbVoisins.getValue();
    }//GEN-LAST:event_spinnerNbVoisinsStateChanged

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if ("vide".equals(villeSelec.getNomVille())) {
            JOptionPane.showMessageDialog(this, "Vous n'avez selectionne aucune ville !", "Bot", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Informations completes sur la ville selectionnee : \n"
                                          + villeSelec.toString() + "\n", "Bot", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void panelGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGraphMouseClicked
        int cordX = evt.getX();
        int cordY = evt.getY();
        for (Ville v : gr.getListe()) {
            boolean trouve = rechercherVille(cordX, cordY, v);
            if (trouve) {
                if (recherche == 0) {
                    villeSelec = v;
                    boutonNomVille.setText(v.getNomVille());
                    String[] type = v.getClass().getName().split("\\.");
                    boutonTypeVille.setText(type[1]);
                }
                else if (recherche == 1) {
                    v1 = v;
                    jLabelVille1.setText("   Ville 1 : " + v.getNomVille());
                    recherche ++;
                } else if (recherche == 2) {
                    v2 = v;
                    jLabelVille2.setText("   Ville 2 : " + v.getNomVille());
                    recherche = 0;
                    panelGraph.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }
            }
        }
    }//GEN-LAST:event_panelGraphMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        villeSelec = new Musee("vide","vide");
        boutonNomVille.setText("Aucune");
        boutonTypeVille.setText("Aucun");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JFileChooser choix = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int res = choix.showOpenDialog(null);
    
        if (res == JFileChooser.APPROVE_OPTION) {
            file = choix.getSelectedFile();
            try {
                ouvertureFile(file);
                JOptionPane.showMessageDialog(this, "Le fichier " + file.getName() + " a bien ete chargé !", "Bot", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Le fichier " + file.getName() + " n'a pas ete ouvert /!\\", "Bot", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void boutonAProposSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonAProposSelectionMouseClicked
        JOptionPane.showMessageDialog(this, "Cliquer sur le bouton recherche puis selectionner \ndeux villes en cliquant dessus. \nEnsuite cliquez sur itineraire puis l'itineraire le plus court sera calcule !\nVous pouvez annuler la selection avec le bouton annuler !", "Bot", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_boutonAProposSelectionMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        recherche ++;
        panelGraph.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        v1 = new Musee("vide", "vide");
        v2 = new Musee("vide", "vide");
        jLabelVille1.setText("   Ville 1 : Aucune");
        jLabelVille2.setText("   Ville 2 : Aucune");
        panelGraph.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        ArrayList<Lien> Pcch = calculerPCCH(v1,v2);
    }//GEN-LAST:event_jButton9MouseClicked

    private void bouttonQuantiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonQuantiteMouseClicked
        JOptionPane.showMessageDialog(this, "Voici les quantitees de chaques type de ville : \nLes restaurants : " + gr.calculerNbrRestaurants() + "\nLes monuments : " + gr.calculerNbrMonument() + "\nLes musees : " + gr.calculerNbrMusee(), "Bot", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bouttonQuantiteMouseClicked

    private void boutonOnOfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonOnOfMouseClicked
        if (voisinOnOf == false) {
            gr.toutCacher();
            boutonOnOf.setText("On");
            for(Ville v : gr.getListe()) {
                if (villeSelec.getNomVille().equals(v.getNomVille())) {
                    if (nbVoisins == 0) {
                        gr.get(gr.getIndice(v)).setVisibilite(true);
                    } else {
                        ArrayList<Ville> li = rechercheVoisins(v);
                        for (Ville v2 : li) {
                            
                            for (Ville vv : gr.getListe()) {
                                if (vv.getNomVille().equals(v2.getNomVille())) {
                                    gr.get(gr.getIndice(vv)).setVisibilite(true);
                                }
                            }
                        }
                    }
                }
            }
            voisinOnOf = true;
        } 
        else {
            gr.toutMontrer();
            boutonOnOf.setText("Of");
            voisinOnOf = false;
        }
        Dessin.clear(panelGraph);
        Dessin.dessinerGraph(panelGraph, gr.getListe(), gr);
    }//GEN-LAST:event_boutonOnOfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton boutonAProposSelection;
    private javax.swing.JLabel boutonNomVille;
    private javax.swing.JButton boutonOnOf;
    private javax.swing.JLabel boutonTypeVille;
    private javax.swing.JButton bouttonAPropos;
    private javax.swing.JPanel bouttonAgrandir;
    private javax.swing.JPanel bouttonFermer;
    private javax.swing.JPanel bouttonMenu;
    private javax.swing.JButton bouttonQuantite;
    private javax.swing.JPanel infosVilleSelec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelVille1;
    private javax.swing.JLabel jLabelVille2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel panelGraph;
    private javax.swing.JSlider sliderTailleSommets;
    private javax.swing.JSpinner spinnerNbVoisins;
    // End of variables declaration//GEN-END:variables
}
